# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
      - 'releases/**'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'

jobs:
  test:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest

    # Docker Hub image that `container-job` executes in
    container: node:${{ matrix.node-version }}

    strategy:
      matrix:
        node-version: [20, 18, 16, 14]
        test-suite: [test, coverage] # Add multiple tests but since they use the same build just do it here

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redislabs/rejson:latest
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: npm ci

      - name: Run ${{ matrix.test-suite }}
        run: npm run ${{ matrix.test-suite }}
        env:
          # The hostname used to communicate with the Redis service container
          REDIS_HOST: redis
          # The default Redis port
          REDIS_PORT: 6379
